### ISSUE TITLE
Change the palette color

### ISSUE THREAD

**Issue by adrianog3** [getomni/gnome-terminal#1]
I suggest changing color `#000000` to `#7A7A7A` to improve the contrast of the autocomplete.

- File: gnome-terminal/colors/Omni/palette
- Line: 9

Before:

![image_2021_03_27T01_37_48_802Z](https://user-images.githubusercontent.com/21218657/112706732-aaf1e300-8e7c-11eb-995a-082a8ac6b9d9.png)

After:

![image_2021_03_27T01_40_33_204Z](https://user-images.githubusercontent.com/21218657/112706733-ad543d00-8e7c-11eb-9a09-6353abdb3254.png)

**Comment by gustavojuneo** [comment]
Thanks for the suggestion @adrianog3, The @Jonatan966 sent a fix and these changes have already been made.
